---
- hosts: localhost
  connection: local
  remote_user: ec2-user
  become: True

  tasks:
  - name: working on boto 
    block:
    - name: ping current host
      pip:
        name: boto
        state: present
    rescue:
    - name: debug rescue
      debug:
        msg: "fall back here"
    always:
    - name: debug info 
      debug:
        msg: "how are you"
  - name: aws configure
    block:
    - name: ec2 config
      ec2:
        image: ami-0dc185deadd3ac449
        instance_type: t2.micro
        region: ap-northeast-1
        instance_tags:
          Name: ansible-ec2
    rescue:
    - name: message failed
      debug:
        msg: "Failed to complete ec2 please export access and secret keys"